AWSTemplateFormatVersion: 2010-09-09
Description: "Deploys a data bucket and config bucket to S3"
Parameters:
  AppName:
    Type: String
  AppVersion:
    Type: String
  Stage:
    Type: String
  DataBucketArn:
    Type: String
  DataBucketName:
    Type: String
Resources:
  VidMasherRDTGlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - !Ref AWS::Region
          - GlueServiceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: !Join
          - '-'
          - - !Ref Stage
            - !Ref AppName
            - !Ref AppVersion
            - !Ref AWS::Region
            - GlueServicePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: 
                  - !Ref DataBucketArn
                  - !Join
                    - ""
                    - - !Ref DataBucketArn
                      - "/*" 
  VidMasherRDTDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Join 
          - '-'
          - - !Ref Stage
            - !Ref AppName
            - !Ref AppVersion
            - database
  SubredditDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Join 
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - !Ref AWS::Region
          - subreddit-crawler
      Role: !GetAtt VidMasherRDTGlueRole.Arn
      Targets:
        S3Targets:
          - Path: !Join ['', [s3://, !Ref DataBucketName, /data/raw_reddit_posts_json]]
      DatabaseName: !Ref VidMasherRDTDatabase
      TablePrefix: !Join ['_', [!Ref Stage, 'vm_rdt', !Ref AppVersion, 'test2', '']]
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
      Schedule:
        ScheduleExpression: cron(0 3/12 * * ? *)
Outputs:
  SubredditDataCrawler:
    Description: Subreddit raw data crawler
    Value: !Ref SubredditDataCrawler
    Export:
      Name: !Sub "${AWS::StackName}-SubredditDataCrawler"
  StackName:
    Description: StackName
    Value: !Sub ${AWS::StackName}