AWSTemplateFormatVersion: 2010-09-09
Description: "Deploys a data bucket and config bucket to S3"
Parameters:
  AppName:
    Type: String
  AppVersion:
    Type: String
  Stage:
    Type: String
  DataBucketArn:
    Type: String
  DataBucketName:
    Type: String
Resources:
  SubredditsDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Join 
          - '-'
          - - !Ref Stage
            - !Ref AppName
            - !Ref AppVersion
            - database
  SubredditDataCrawlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - !Ref AWS::Region
          - subreddit-crawler
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: !Ref AppVersion
            Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref "AWS::AccountId"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: !Join
          - '-'
          - - !Ref Stage
            - !Ref AppName
            - !Ref AppVersion
            - !Ref AWS::Region
            - subreddit-crawler-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource: 
                  - !Ref DataBucketArn
                  - !Join
                    - ''
                    - - !Ref DataBucketArn
                      - '/*' 
  SubredditDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Join 
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - !Ref AWS::Region
          - subreddit-crawler
      Role: !GetAtt SubredditDataCrawlerRole.Arn
      Targets:
        S3Targets:
          - Path: !Join ['', [s3://, !Ref DataBucketName, /data/raw_reddit_posts_json]]
      DatabaseName: !Ref SubredditsDatabase
      TablePrefix: ssrp_
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
      Schedule:
        ScheduleExpression: cron(0 3 * * ? *)
  RedditDataWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties: 
      Name: !Join 
        - '-'
        - - !Ref Stage
          - !Ref AppName
          - !Ref AppVersion
          - !Ref AWS::Region
          - athena-workgroup
      State: ENABLED
Outputs:
  SubredditDataCrawler:
    Description: Subreddit raw data crawler
    Value: !Ref SubredditDataCrawler
    Export:
      Name: !Sub '${AWS::StackName}-SubredditDataCrawler'
  RedditDataWorkgroup:
    Description: Athena workgroup for Reddit data
    Value: !Ref RedditDataWorkgroup
    Export:
      Name: !Sub '${AWS::StackName}-RedditDataWorkgroup'
  StackName:
    Description: StackName
    Value: !Sub '${AWS::StackName}'